AB#629 carnival new styles
cognizant-softvision/donate-to pull request #438
Opened 2020-09-02 21:11 UTC by franciscoghersi

2020-09-02 21:24 UTC, oonosan commented on src/DonateTo.WebApplication/ClientApp/src/app/app.component.html
> +  <nz-footer style="text-align: center;">© 2020 Softvision. All rights reserved.</nz-footer>
Shouldn't we use a translate pipe here?

2020-09-02 21:31 UTC, oonosan commented on src/DonateTo.WebApplication/ClientApp/src/styles.less
> +  border-radius: 6px !important;
Use em, please

2020-09-02 21:31 UTC, oonosan commented on src/DonateTo.WebApplication/ClientApp/src/styles.less
> +  border-radius: 6px !important;
Please change px values to em

2020-09-02 21:34 UTC, matigrieben requested changes

2020-09-02 21:34 UTC, matigrieben commented on src/DonateTo.WebApplication/ClientApp/src/styles.less
> +  border-radius: 6px !important;
We don't use px, please change that to em

2020-09-02 21:34 UTC, matigrieben commented on src/DonateTo.WebApplication/ClientApp/src/styles.less
> +  border-radius: 6px !important;
We don't use px, please change that to em

2020-09-02 21:34 UTC, matigrieben commented on src/DonateTo.WebApplication/ClientApp/src/app/app.component.html
> +  <nz-footer style="text-align: center;">© 2020 Softvision. All rights reserved.</nz-footer>
@Faculewis What do you think?

2020-09-02 23:24 UTC, facundo-lewis commented on src/DonateTo.WebApplication/ClientApp/src/app/app.component.html
> +  <nz-footer style="text-align: center;">© 2020 Softvision. All rights reserved.</nz-footer>
- Remove that message an change it for some text like this:
**For suppport contact support@donate.com**
- It should be in both languages

2020-09-03 14:17 UTC, matigrieben approved these changes

2020-09-03 14:17 UTC, merged